### ISSUE TITLE
src() method doesn't work when module is used within another module

### ISSUE THREAD

**Issue by markbirbeck** [markbirbeck/stream-google-spreadsheet#1]
when incorporating this module into `sifttt` we get the following error:

```
[12:34:43] TypeError: object is not a function
    at module.exports.src (/Users/markbirbeck/Documents/workspace/_norepo/sifttt/node_modules/stream-google-spreadsheet/index.js:157:14)
    at Gulp.<anonymous> (/Users/markbirbeck/Documents/workspace/_norepo/sifttt/index.js:22:12)
    at module.exports (/Users/markbirbeck/Documents/workspace/_norepo/calendar.place-sifttt/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/markbirbeck/Documents/workspace/_norepo/calendar.place-sifttt/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/markbirbeck/Documents/workspace/_norepo/calendar.place-sifttt/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/markbirbeck/Documents/workspace/_norepo/calendar.place-sifttt/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/markbirbeck/Documents/workspace/_norepo/calendar.place-sifttt/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by markbirbeck** [comment]
At the end of the `src()` method we have this:

``` javascript

  return this(glob, opt)
    .map(toVinyl);
```

It seems that the `this` part doesn't work when nested a further level down. Not sure why but it doesn't really matter...it's probably better not to have code like this anyway.
